[nfs]
172.31.23.52 ansible_ssh_user='ec2-user' 

[webservers]
172.31.20.82 ansible_ssh_user='ec2-user' 
172.31.27.24 ansible_ssh_user='ec2-user' 
172.31.20.165 ansible_ssh_user='ec2-user' 

[db]
172.31.25.230 ansible_ssh_user='ubuntu' 

[lb]
172.31.21.200 ansible_ssh_user='ubuntu' 

[localconnection]
localhost ansible_connection=local

