---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

    - name: create a temp folder
      file:
        path: /tmp/newfolder/file
        state: directory

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

    - name: create a temp folder
      file:
        path: /tmp/newfolder/file
        state: directory

    - name: Set timezone
      command: timedatectl set-timezone Africa/Lagos

    - name: Execute sample script
      script: ~/ansible-config-mgt/script.sh
